### ISSUE TITLE
Poweredby Mobile Hide

### ISSUE THREAD

**Issue by mattcam** [Tracardi/uix-consent#1]
**Describe the solution you'd like**
As a visitor browsing a website that uses the Tracardi UIX consent widget on a mobile device, I would like the "Powered by Tracardi" logo not to be displayed so that options on the widget can be selected easily.

**Describe alternatives you've considered**
When this issue was identified, the only solution was to edit the UIX consent file in production on the Tracardi API, which, while a workaround, is not ideal.

**Comment by atompie** [comment]
Will be available in 1.0.0
